# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1112, 628)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../New version/EduTrackingPublic/icons/person.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("\n"
"/* Set image as background for main window  */\n"
"#Dialog {\n"
"    border-image: url(:/icons_qrc/526622.jpg); \n"
"/*border-image: url(:/icons/15576a3c2ad9502.jpg);*/\n"
"\n"
"}\n"
"/* Set style for function widget */\n"
"#widget {\n"
"    background-color: rgb(50, 65, 75);\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"/* Set style for Qlabel */\n"
"QLabel {\n"
"    color: #fff;\n"
"font: 75 14pt \"Motken K Sina\";\n"
"}\n"
"\n"
"/* Set style for QLineEdit */\n"
"QLineEdit {\n"
"    background-color: #5b586e;\n"
"    border-radius:10px;\n"
"    padding: 5px 0;\n"
"    border: 1px solid #5b586e;\n"
"    color: #fff;\n"
"    font: 75 10pt \"Motken K Sina\";\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #8b86aa;\n"
"    background-color: #343155;\n"
"}\n"
"\n"
"/* Set style for QPushButton */\n"
"QPushButton {\n"
"    background-color: #0d6efd;\n"
"    border: 1px solid #343155;\n"
"    color: #fff;\n"
"    padding: 6px;\n"
"    margin-top: 20px;\n"
"    border-radius:20px;\n"
"    font: 75 10pt \"Motken K Sina\";\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:clicked {\n"
"    background-color: #0b5ed7;\n"
"    border: 1px solid #9ac3fe;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnClose = QtWidgets.QPushButton(self.frame)
        self.btnClose.setGeometry(QtCore.QRect(280, -20, 55, 61))
        self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClose.setStyleSheet("\n"
"\n"
"\n"
"QPushButton {\n"
"background-color:none;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(50, 65, 75);\n"
"\n"
"       \n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.btnClose.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons_qrc/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon1)
        self.btnClose.setIconSize(QtCore.QSize(30, 30))
        self.btnClose.setObjectName("btnClose")
        self.gridLayout_2.addWidget(self.frame, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(329, 314, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(328, 314, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 77, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 76, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 1, 1, 1)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setMinimumSize(QtCore.QSize(400, 0))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Motken K Sina")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("Motken K Sina")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons_qrc/userProfile.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtUserNameLogin = QtWidgets.QLineEdit(self.widget)
        self.txtUserNameLogin.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Motken K Sina")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.txtUserNameLogin.setFont(font)
        self.txtUserNameLogin.setObjectName("txtUserNameLogin")
        self.verticalLayout.addWidget(self.txtUserNameLogin)
        self.txtPasswordUserLogin = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Motken K Sina")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.txtPasswordUserLogin.setFont(font)
        self.txtPasswordUserLogin.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPasswordUserLogin.setObjectName("txtPasswordUserLogin")
        self.verticalLayout.addWidget(self.txtPasswordUserLogin)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnLoginUser = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoginUser.sizePolicy().hasHeightForWidth())
        self.btnLoginUser.setSizePolicy(sizePolicy)
        self.btnLoginUser.setMaximumSize(QtCore.QSize(150, 250))
        self.btnLoginUser.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnLoginUser.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Motken K Sina")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnLoginUser.setFont(font)
        self.btnLoginUser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnLoginUser.setDefault(False)
        self.btnLoginUser.setFlat(True)
        self.btnLoginUser.setObjectName("btnLoginUser")
        self.horizontalLayout_2.addWidget(self.btnLoginUser)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txtUserNameLogin, self.txtPasswordUserLogin)
        Dialog.setTabOrder(self.txtPasswordUserLogin, self.btnLoginUser)
        Dialog.setTabOrder(self.btnLoginUser, self.btnClose)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "تسجيل الدخول "))
        self.txtUserNameLogin.setPlaceholderText(_translate("Dialog", "إسم المستخدم "))
        self.txtPasswordUserLogin.setPlaceholderText(_translate("Dialog", "كلمة السر "))
        self.btnLoginUser.setText(_translate("Dialog", "دخـــــــــــول"))
from icons_rc import icons